# Seed data for projects and posts

PROJECTS_SEED = [
    {
        "id": "northwind-analytics",
        "title": "Northwind Analytics",
        "category": "Dashboard",
        "year": 2025,
        "description": "A real-time SaaS analytics dashboard with customizable widgets, role-based access, and dark-mode first visuals.",
        "tech": ["Next.js", "TypeScript", "Tailwind", "Recharts"],
        "image": "https://images.unsplash.com/photo-1551288049-bebda4e38f71",
        "link": "#",
        "featured": True,
        "order": 1,
    },
    {
        "id": "arbor-ecommerce",
        "title": "Arbor Commerce",
        "category": "E-commerce",
        "year": 2025,
        "description": "Headless storefront for a sustainable furniture brand. Blazing-fast, AA accessible, and built for editorial storytelling.",
        "tech": ["Next.js", "Shopify", "GSAP", "Sanity"],
        "image": "https://images.unsplash.com/photo-1547658719-da2b51169166",
        "link": "#",
        "featured": False,
        "order": 2,
    },
    {
        "id": "pulse-mobile",
        "title": "Pulse — Fitness App",
        "category": "Mobile Web",
        "year": 2024,
        "description": "A PWA that guides users through AI-curated workouts with haptic feedback and offline support.",
        "tech": ["React", "Workbox", "Framer Motion"],
        "image": "https://images.pexels.com/photos/27141316/pexels-photo-27141316.jpeg",
        "link": "#",
        "featured": False,
        "order": 3,
    },
    {
        "id": "lumen-cms",
        "title": "Lumen CMS",
        "category": "Platform",
        "year": 2024,
        "description": "An internal content platform for a newsroom; reduced publishing time by 62% with an editor-first UX.",
        "tech": ["React", "Node.js", "Postgres", "tRPC"],
        "image": "https://images.unsplash.com/photo-1618424562492-f778e25652a1",
        "link": "#",
        "featured": True,
        "order": 4,
    },
    {
        "id": "fieldnotes-blog",
        "title": "Field Notes",
        "category": "Editorial",
        "year": 2023,
        "description": "A longform reading experience for independent journalists with thoughtful typography and distraction-free layouts.",
        "tech": ["Astro", "MDX", "Vercel"],
        "image": "https://images.pexels.com/photos/34803969/pexels-photo-34803969.jpeg",
        "link": "#",
        "featured": False,
        "order": 5,
    },
    {
        "id": "orbit-landing",
        "title": "Orbit Landing",
        "category": "Marketing",
        "year": 2023,
        "description": "High-converting marketing site for a B2B SaaS — 98 Lighthouse and a 3.4x lift in signups.",
        "tech": ["Next.js", "Tailwind", "Framer Motion"],
        "image": "https://images.pexels.com/photos/3888149/pexels-photo-3888149.jpeg",
        "link": "#",
        "featured": False,
        "order": 6,
    },
]

POSTS_SEED = [
    {
        "id": "designing-for-calm",
        "title": "Designing for calm: interfaces that respect attention",
        "excerpt": "Notes on building software that fades into the background so people can focus on their actual work.",
        "date": "June 14, 2025",
        "read_time": "6 min",
        "tag": "Design",
        "cover": "https://images.unsplash.com/photo-1618424562492-f778e25652a1",
        "body": [
            "Good interfaces are quiet. They don't demand your attention; they reward it. When we design tools that respect the user's time and focus, we unlock a kind of software that feels like a good conversation — one where the other side listens carefully before responding.",
            "The smallest details — focus states, empty states, the way a button hesitates before confirming a destructive action — are what separate competent work from craft. They take time, and they almost never show up on roadmaps. Ship them anyway.",
            "Designing for calm isn't about removing features. It's about choosing where to spend the user's attention budget. The best products make that budget feel generous.",
            "Thanks for reading. If this resonated, I'd love to hear from you.",
        ],
    },
    {
        "id": "css-has-year",
        "title": "The year CSS :has() changed how I build components",
        "excerpt": "A practical tour of parent selectors, container queries, and the small revolutions hiding in modern CSS.",
        "date": "May 02, 2025",
        "read_time": "8 min",
        "tag": "CSS",
        "cover": "https://images.pexels.com/photos/34803969/pexels-photo-34803969.jpeg",
        "body": [
            "For years, CSS was a language without a parent selector. That one limitation shaped how we named classes, structured components, and reached for JavaScript to solve styling problems that should have been one line of CSS.",
            ":has() changes all of that. Combined with container queries and :not(), modern CSS can express component state without adding a single class.",
            "Here's a pattern I use constantly: a form field that styles its label based on whether the input is focused, filled, or invalid — all from CSS, no JavaScript.",
            "The takeaway: re-evaluate the rules you've internalized. The web platform quietly caught up to the problems we used to solve in code.",
        ],
    },
    {
        "id": "ship-fewer-features",
        "title": "Ship fewer features. Sharpen the ones that matter.",
        "excerpt": "A gentle argument against roadmap bloat and a framework I use to kill features I'm secretly in love with.",
        "date": "March 21, 2025",
        "read_time": "5 min",
        "tag": "Craft",
        "cover": "https://images.unsplash.com/photo-1551288049-bebda4e38f71",
        "body": [
            "Every product I've shipped has been improved by the features we chose not to build. Scope is a scalpel, not a warehouse.",
            "The framework I use is simple: for every feature on the roadmap, ask 'what would have to be true for this to be the single most important thing we ship this quarter?' If you can't answer without hand-waving, it doesn't belong in the next release.",
            "This isn't about doing less. It's about going deeper on fewer things. Users don't remember your feature list; they remember how your product made them feel.",
            "Cut with love. Ship with conviction.",
        ],
    },
]
